module.exports = {
    APP_SERVER_ERR: 101,
    TEST: 0,
    TEMP_FILE_SAVE_ERR: 1,
    WRONG_FILE_TYPE_UPLOADED_ERR: 2,
    TEMP_FILE_UNLINK_ERR: 3,
    TEMP_FILE_STAT_ERR:4,
    TEMP_FILE_PATH_NOT_FOUND_ERR: 5,
    TEMP_FILE_DIGESTION_ERR: 6,
    QUERY_ERR: 7,
    QUESTION_NOT_FOUND_ERR: 8,
    DATA_NOT_AVAILABLE_ERR: 9,
    USER_SEARCH_ERR: 10,
    QSET_NOT_AVAILABLE_ERR: 11,
    NOT_FOUND: 12,
    NOT_IN_DB_ERR: 13
}

var errMsg = {
    101: 'APP_SERVER_ERR',
    0 : 'TEST',
    1 : 'TEMP_FILE_SAVE_ERR',
    2 : 'WRONG_FILE_TYPE_UPLOADED_ERR',
    3 : 'TEMP_FILE_UNLINK_ERR',
    4 : 'TEMP_FILE_STAT_ERR:',
    5 : 'TEMP_FILE_PATH_NOT_FOUND_ERR',
    6 : 'TEMP_FILE_DIGESTION_ERR',
    7 : 'QUERY_ERR',
    8 : 'QUESTION_NOT_FOUND_ERR',
    9 : 'DATA_NOT_AVAILABLE_ERR',
    10 : 'USER_SEARCH_ERR',
    11 : 'QSET_NOT_AVAILABLE_ERR'

}